-- PYTH BOMB: question bank, batch 3 (120 questions, translated to English)
-- Run in Supabase SQL Editor. Safe to run more than once (duplicate question text is skipped).
-- Pyth questions and one crypto one are verified = false until Halls checks them.
-- To approve the Pyth ones after checking:
--   update public.questions set verified = true where source_reference like 'Halls batch 3 (Pyth%' and verified = false;
-- Answers are compared in lowercase, without accents or punctuation (so "Pelé" = "pele").

insert into public.questions (category, difficulty, text, accepted_answers, source_reference, verified) values
  ('movies', 'easy', 'Which epic HBO series is set mainly in Westeros?', array['Game of Thrones', 'GoT'], 'Halls batch 3', true),
  ('movies', 'easy', 'In Forrest Gump, life is compared to which sweet treat?', array['box of chocolates', 'a box of chocolates', 'chocolates'], 'Halls batch 3', true),
  ('movies', 'easy', 'Who is the famous heavy-breathing villain of the classic Star Wars saga?', array['Darth Vader', 'Vader'], 'Halls batch 3', true),
  ('movies', 'easy', 'Which tree-shaped Marvel hero can only say his own name?', array['Groot', 'I am Groot'], 'Halls batch 3', true),
  ('movies', 'easy', 'Which classic James Cameron film is set on a ship that sank in 1912?', array['Titanic', 'the Titanic'], 'Halls batch 3', true),
  ('movies', 'medium', 'Who directed the acclaimed film Pulp Fiction?', array['Quentin Tarantino', 'Tarantino'], 'Halls batch 3', true),
  ('movies', 'medium', 'Which car model is turned into a time machine in Back to the Future?', array['DeLorean', 'DMC DeLorean', 'DMC-12'], 'Halls batch 3', true),
  ('movies', 'easy', 'What is the dark parallel dimension in Stranger Things called?', array['Upside Down', 'the Upside Down'], 'Halls batch 3', true),
  ('movies', 'medium', 'In which European city does the original heist of Money Heist (La Casa de Papel) take place?', array['Madrid'], 'Halls batch 3', true),
  ('movies', 'medium', 'Who masterfully played the Joker in Batman: The Dark Knight (2008)?', array['Heath Ledger', 'Ledger'], 'Halls batch 3', true),
  ('movies', 'easy', 'Which Pixar animation tells the story of a house that flies away with balloons?', array['Up'], 'Halls batch 3', true),
  ('movies', 'easy', 'Which superhero gets his powers after being bitten by a radioactive spider?', array['Spider-Man', 'Spiderman', 'Spider Man', 'Peter Parker'], 'Halls batch 3', true),
  ('movies', 'easy', 'Which actor stars in the Mission: Impossible action franchise?', array['Tom Cruise', 'Cruise'], 'Halls batch 3', true),
  ('movies', 'easy', 'In The Lord of the Rings, who carries the responsibility of destroying the One Ring?', array['Frodo', 'Frodo Baggins'], 'Halls batch 3', true),
  ('movies', 'easy', 'In which fictional town does the family from The Simpsons live?', array['Springfield'], 'Halls batch 3', true),
  ('movies', 'easy', 'Which Hogwarts house has a lion as its symbol?', array['Gryffindor'], 'Halls batch 3', true),
  ('fun', 'medium', 'Which tactical shooter from Valve officially replaced the famous CS:GO?', array['Counter-Strike 2', 'CS2', 'Counter Strike 2'], 'Halls batch 3', true),
  ('fun', 'medium', 'In League of Legends, what is the role called for a player who stays in the neutral monster area instead of the lanes?', array['Jungle', 'Jungler'], 'Halls batch 3', true),
  ('fun', 'easy', 'What is the oldest, most valuable and most famous cryptocurrency in the world?', array['Bitcoin', 'BTC'], 'Halls batch 3', true),
  ('fun', 'easy', 'Which tech company makes the iPhone?', array['Apple'], 'Halls batch 3', true),
  ('fun', 'easy', 'Which block-based survival game was created by Notch?', array['Minecraft'], 'Halls batch 3', true),
  ('fun', 'easy', 'What is the name of the princess in the pink dress who is often rescued by Mario?', array['Princess Peach', 'Peach'], 'Halls batch 3', true),
  ('fun', 'easy', 'Which South African entrepreneur founded SpaceX and runs Tesla?', array['Elon Musk', 'Musk'], 'Halls batch 3', true),
  ('fun', 'medium', 'What does the acronym NPC mean in video games?', array['Non-Player Character', 'Non Playable Character', 'Non-Playable Character', 'Non Player Character'], 'Halls batch 3', true),
  ('fun', 'easy', 'Which Nintendo hybrid console lets you play both on the TV and in handheld mode?', array['Nintendo Switch', 'Switch'], 'Halls batch 3', true),
  ('fun', 'easy', 'Which hero in a green hat and tunic stars in The Legend of Zelda?', array['Link'], 'Halls batch 3', true),
  ('fun', 'easy', 'Which short-video platform made the famous "dances" popular worldwide?', array['TikTok', 'Tik Tok'], 'Halls batch 3', true),
  ('fun', 'easy', 'In games like Fortnite, what is the mode called where the last one standing wins?', array['Battle Royale', 'BR'], 'Halls batch 3', true),
  ('fun', 'easy', 'What is the mobile operating system created by Google?', array['Android'], 'Halls batch 3', true),
  ('fun', 'easy', 'What was the social network with the little blue bird, now known as "X", called?', array['Twitter'], 'Halls batch 3', true),
  ('fun', 'easy', 'Which classic arcade game has you eat dots and run away from ghosts?', array['Pac-Man', 'Pacman', 'Pac Man'], 'Halls batch 3', true),
  ('fun', 'easy', 'In which famous franchise do you catch and train pocket creatures using balls?', array['Pokemon', 'Pokémon'], 'Halls batch 3', true),
  ('fun', 'easy', 'Which famous conversational AI was created by OpenAI?', array['ChatGPT', 'Chat GPT'], 'Halls batch 3', true),
  ('fun', 'medium', 'Which virtual reality headset belongs to Meta?', array['Meta Quest', 'Quest', 'Oculus Quest', 'Oculus'], 'Halls batch 3', true),
  ('fun', 'medium', 'What is the name of the technology behind cryptocurrencies that stores transactions in linked blocks?', array['Blockchain', 'Block chain'], 'Halls batch 3', true),
  ('fun', 'easy', 'Which classic video game about fitting falling geometric pieces came from Russia?', array['Tetris'], 'Halls batch 3', true),
  ('sports', 'easy', 'Which famous California NBA team wears purple and gold?', array['Los Angeles Lakers', 'LA Lakers', 'Lakers'], 'Halls batch 3', true),
  ('sports', 'easy', 'How often do the Summer Olympic Games take place?', array['every 4 years', '4 years', 'every four years', 'four years', '4', 'four'], 'Halls batch 3', true),
  ('sports', 'easy', 'Which legendary Brazilian football player is known worldwide as "The King"?', array['Pele', 'Pelé'], 'Halls batch 3', true),
  ('sports', 'easy', 'Which South American country hosted the 2014 FIFA World Cup?', array['Brazil', 'Brasil'], 'Halls batch 3', true),
  ('sports', 'easy', 'How many players from each team start a basketball game on the court?', array['5', 'five'], 'Halls batch 3', true),
  ('sports', 'medium', 'Which Brazilian driver became a three-time Formula 1 world champion?', array['Ayrton Senna', 'Senna'], 'Halls batch 3', true),
  ('sports', 'easy', 'How many pins must be knocked down at the end of the lane in a standard bowling game?', array['10', 'ten'], 'Halls batch 3', true),
  ('sports', 'easy', 'In chess, which piece moves only diagonally?', array['Bishop', 'the bishop'], 'Halls batch 3', true),
  ('sports', 'easy', 'The Super Bowl is the final of which sport?', array['American football', 'football', 'NFL'], 'Halls batch 3', true),
  ('sports', 'medium', 'Which Asian country is known as the birthplace of Judo?', array['Japan'], 'Halls batch 3', true),
  ('sports', 'medium', 'Which American swimmer won a record 28 Olympic medals?', array['Michael Phelps', 'Phelps'], 'Halls batch 3', true),
  ('sports', 'easy', 'In football (soccer), which card color sends a player off immediately?', array['red', 'red card'], 'Halls batch 3', true),
  ('sports', 'easy', 'In which winter sport do players use a hard rubber puck instead of a ball?', array['ice hockey', 'hockey'], 'Halls batch 3', true),
  ('sports', 'medium', 'Which Spanish football team plays its home games at the Santiago Bernabéu?', array['Real Madrid'], 'Halls batch 3', true),
  ('sports', 'medium', 'In the English league, which London club is traditionally nicknamed "The Gunners"?', array['Arsenal'], 'Halls batch 3', true),
  ('sports', 'medium', 'Usain Bolt holds world records in which sport?', array['athletics', 'track and field', 'track', 'sprinting', 'running'], 'Halls batch 3', true),
  ('sports', 'medium', 'Which North American archipelago is historically the birthplace of surfing?', array['Hawaii', 'Hawaiian Islands'], 'Halls batch 3', true),
  ('sports', 'easy', 'In which martial art do competitors fight wearing thick gloves inside a ring surrounded by ropes?', array['boxing'], 'Halls batch 3', true),
  ('general', 'easy', 'What is the largest country in the world by land area?', array['Russia'], 'Halls batch 3', true),
  ('general', 'easy', 'On which continent is the Sahara desert located?', array['Africa'], 'Halls batch 3', true),
  ('general', 'medium', 'Which huge Brazilian river runs through the largest rainforest in the world?', array['Amazon', 'Amazon River', 'Rio Amazonas'], 'Halls batch 3', true),
  ('general', 'medium', 'In which South American country are the Inca ruins of Machu Picchu?', array['Peru'], 'Halls batch 3', true),
  ('general', 'medium', 'In which Brazilian city is the famous Copacabana wave-pattern promenade?', array['Rio de Janeiro', 'Rio'], 'Halls batch 3', true),
  ('general', 'medium', 'Which very cold US state is separated from the rest of the country and is close to Russia?', array['Alaska'], 'Halls batch 3', true),
  ('general', 'easy', 'The Eiffel Tower is in which European capital?', array['Paris'], 'Halls batch 3', true),
  ('general', 'easy', 'Which European country is shaped like a boot?', array['Italy'], 'Halls batch 3', true),
  ('general', 'medium', 'Which man-made canal in Central America links the Atlantic to the Pacific?', array['Panama Canal', 'the Panama Canal'], 'Halls batch 3', true),
  ('general', 'medium', 'What is the capital of Australia?', array['Canberra'], 'Halls batch 3', true),
  ('general', 'easy', 'Big Ben is located in which capital city?', array['London'], 'Halls batch 3', true),
  ('general', 'hard', 'Which desert, located mainly in Chile, is considered the driest in the world?', array['Atacama', 'Atacama Desert'], 'Halls batch 3', true),
  ('general', 'easy', 'What are the two colors on the flag of Canada?', array['red and white', 'red white', 'white and red'], 'Halls batch 3', true),
  ('general', 'easy', 'What is the main official language spoken by the population of Mexico?', array['Spanish'], 'Halls batch 3', true),
  ('general', 'medium', 'In which Brazilian state is Sugarloaf Mountain located?', array['Rio de Janeiro', 'Rio'], 'Halls batch 3', true),
  ('general', 'easy', 'What is the highest mountain on planet Earth?', array['Mount Everest', 'Everest'], 'Halls batch 3', true),
  ('general', 'easy', 'In which country are the Pyramids of Giza?', array['Egypt'], 'Halls batch 3', true),
  ('general', 'easy', 'Who painted the Mona Lisa?', array['Leonardo da Vinci', 'da Vinci', 'Leonardo'], 'Halls batch 3', true),
  ('general', 'easy', 'Which domestic feline animal is famous for dominating the internet with funny videos?', array['cat', 'a cat'], 'Halls batch 3', true),
  ('general', 'medium', 'Which protein supplement extracted from milk is the most consumed in the fitness world?', array['whey protein', 'whey'], 'Halls batch 3', true),
  ('general', 'easy', 'What is the name of Mickey Mouse''s yellow dog?', array['Pluto'], 'Halls batch 3', true),
  ('general', 'easy', 'How many strings does a traditional guitar have?', array['6', 'six'], 'Halls batch 3', true),
  ('general', 'easy', 'Which flightless bird is native to Antarctica?', array['penguin', 'a penguin'], 'Halls batch 3', true),
  ('general', 'easy', 'On which mountain did the main Greek gods live?', array['Mount Olympus', 'Olympus'], 'Halls batch 3', true),
  ('general', 'easy', 'Who wrote Romeo and Juliet?', array['William Shakespeare', 'Shakespeare'], 'Halls batch 3', true),
  ('general', 'easy', 'Who released the album Thriller and became known as the King of Pop?', array['Michael Jackson'], 'Halls batch 3', true),
  ('general', 'easy', 'What is measured in Celsius or Fahrenheit?', array['temperature'], 'Halls batch 3', true),
  ('general', 'easy', 'What color is human blood when it is rich in oxygen?', array['red', 'bright red'], 'Halls batch 3', true),
  ('general', 'medium', 'In which great geological era did the dinosaurs live?', array['Mesozoic', 'Mesozoic Era'], 'Halls batch 3', true),
  ('general', 'easy', 'How many hours make up a day?', array['24', 'twenty four'], 'Halls batch 3', true),
  ('general', 'easy', 'Which month usually has only 28 days?', array['February'], 'Halls batch 3', true),
  ('general', 'easy', 'In a children''s game, what is passed from hand to hand until someone "gets burned"?', array['hot potato', 'the hot potato'], 'Halls batch 3', true),
  ('general', 'easy', 'What is the natural satellite of the Earth?', array['Moon', 'the Moon'], 'Halls batch 3', true),
  ('general', 'easy', 'How many climate seasons make up a year?', array['4', 'four'], 'Halls batch 3', true),
  ('general', 'medium', 'What does DeFi stand for?', array['Decentralized Finance', 'Decentralised Finance'], 'Halls batch 3', true),
  ('general', 'medium', 'What does WAGMI stand for?', array['We''re All Gonna Make It', 'We are all gonna make it', 'We all gonna make it', 'We are all going to make it'], 'Halls batch 3', true),
  ('general', 'medium', 'What is the fee paid to process a transaction on a blockchain called?', array['gas', 'gas fee', 'gas fees'], 'Halls batch 3', true),
  ('general', 'medium', 'What does NFT stand for?', array['Non-Fungible Token', 'Non Fungible Token'], 'Halls batch 3', true),
  ('general', 'medium', 'Which event cuts the miners'' reward for Bitcoin in half?', array['halving', 'the halving', 'bitcoin halving'], 'Halls batch 3', true),
  ('general', 'medium', 'What are crypto wallets that stay offline called?', array['cold wallet', 'cold wallets', 'cold storage'], 'Halls batch 3', true),
  ('general', 'easy', 'What is the free distribution of tokens to a community or early users called?', array['airdrop', 'an airdrop'], 'Halls batch 3', true),
  ('general', 'hard', 'Which upgrade moved Ethereum to Proof of Stake?', array['The Merge', 'Merge'], 'Halls batch 3', true),
  ('general', 'easy', 'Which meme cryptocurrency inspired by a Shiba Inu became famous thanks to Elon Musk?', array['Dogecoin', 'DOGE'], 'Halls batch 3', true),
  ('general', 'medium', 'What do we call a program that runs by itself on a blockchain once its conditions are met?', array['smart contract', 'smart contracts'], 'Halls batch 3', true),
  ('general', 'medium', 'What does DAO stand for?', array['Decentralized Autonomous Organization', 'Decentralised Autonomous Organisation'], 'Halls batch 3', true),
  ('general', 'medium', 'What is the set of 12 or 24 words used to recover a crypto wallet called?', array['seed phrase', 'recovery phrase', 'secret recovery phrase', 'mnemonic phrase'], 'Halls batch 3', true),
  ('general', 'medium', 'Which acronym stands for Fear, Uncertainty and Doubt?', array['FUD'], 'Halls batch 3', true),
  ('general', 'hard', 'Which L1 known for parallel execution has community projects like Chog and Spiky Nads?', array['Monad'], 'Halls batch 3', false),
  ('pyth', 'medium', 'What kind of data is it called when Pyth gets prices straight from exchanges and market makers, with no middlemen?', array['first-party data', 'first party data', 'first-party', 'first party'], 'Halls batch 3 (Pyth, to be checked)', false),
  ('pyth', 'medium', 'Which Pyth product provides verifiable random numbers for games and NFTs?', array['Pyth Entropy', 'Entropy'], 'Halls batch 3 (Pyth, to be checked)', false),
  ('pyth', 'medium', 'Which blockchain was Pyth''s original architecture designed to take advantage of?', array['Solana'], 'Halls batch 3 (Pyth, to be checked)', false),
  ('pyth', 'medium', 'Which cross-chain protocol did Pyth historically use to distribute its price feeds?', array['Wormhole'], 'Halls batch 3 (Pyth, to be checked)', false),
  ('pyth', 'medium', 'What is the PYTH token mainly used for?', array['governance', 'staking', 'governance and staking'], 'Halls batch 3 (Pyth, to be checked)', false),
  ('pyth', 'hard', 'In which month and year did the PYTH retroactive airdrop happen?', array['November 2023', 'Nov 2023', '11/2023'], 'Halls batch 3 (Pyth, to be checked)', false),
  ('pyth', 'medium', 'Besides crypto, name one other kind of asset Pyth provides prices for.', array['stocks', 'equities', 'forex', 'fx', 'etfs', 'etf', 'commodities', 'commodity'], 'Halls batch 3 (Pyth, to be checked)', false),
  ('pyth', 'hard', 'What is the maximum supply of PYTH?', array['10 billion', '10B', '10,000,000,000'], 'Halls batch 3 (Pyth, to be checked)', false),
  ('pyth', 'medium', 'Which Pyth service is used to access accurate historical price data?', array['Pyth Benchmarks', 'Benchmarks'], 'Halls batch 3 (Pyth, to be checked)', false),
  ('pyth', 'hard', 'Pyth Core currently delivers data to more than how many blockchains?', array['100', 'more than 100', 'over 100'], 'Halls batch 3 (Pyth, to be checked)', false),
  ('pyth', 'hard', 'What does Pyth publish alongside each price to show how uncertain it is?', array['confidence interval', 'confidence', 'the confidence interval'], 'Halls batch 3 (Pyth, to be checked)', false),
  ('pyth', 'hard', 'Which of these companies was one of Pyth''s first data providers: Nubank, Jane Street or Robinhood?', array['Jane Street', 'Jane'], 'Halls batch 3 (Pyth, to be checked)', false),
  ('pyth', 'hard', 'What is the name of the Swiss association responsible for fostering the Pyth ecosystem?', array['Pyth Data Association', 'Data Association'], 'Halls batch 3 (Pyth, to be checked)', false),
  ('general', 'medium', 'Where was the famous oracle of Ancient Greece located?', array['Delphi'], 'Halls batch 3', true),
  ('general', 'easy', 'Who is the ruler of Mount Olympus and god of thunder?', array['Zeus'], 'Halls batch 3', true),
  ('general', 'easy', 'Which warrior was invulnerable except for his heel?', array['Achilles'], 'Halls batch 3', true),
  ('general', 'medium', 'Which god of the seas and earthquakes wields a trident?', array['Poseidon'], 'Halls batch 3', true),
  ('general', 'medium', 'Who is the Greek goddess of wisdom and military strategy, patron of Athens?', array['Athena', 'Athene'], 'Halls batch 3', true)
on conflict do nothing;
